# **1. Linear Layer**

* 신경망의 가장 기본 구성 요소
* Fully - connected(FC) Layer라고 불리기도 함
* 내부 파라미터에 따른 선형 변환을 수행하는 함수

# **2. Linear Layer 작동 방식**

* 각 입력 노드들에 weight(가중치)를 곱하고 모두 합친 뒤, bias(편향)을 더함
* 행렬곱으로 구현가능함
* n차원에서 m차원으로 선형 변환 함수
* 이 함수의 파라미터를 조절하면 주어진 입력에 대해 원하는 출력을 만들 수 있음

In [ ]:
import torch

In [ ]:
x = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])
y = torch.FloatTensor([[1,2],
                       [1,2]])
print(x.size(), y.size())

torch.Size([3, 2]) torch.Size([2, 2])


In [ ]:
z = torch.matmul(x,y)
print(z.size())

torch.Size([3, 2])


In [ ]:
# Weight(가중치)
W = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])
# bias(현향)
b = torch.FloatTensor([2,2])

In [ ]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [ ]:
def linear(x,W,b):
  y = torch.matmul(x,W) + b # 각 노드의 입력값과 가중치를 곱하고, 편향을 더함
  return y

In [ ]:
x = torch.FloatTensor([[1,1,1],
                      [2,2,2],
                      [3,3,3],
                      [4,4,4]])
print(x.size())

torch.Size([4, 3])


In [ ]:
y = linear(x,W,b)

In [ ]:
print(y.size())

torch.Size([4, 2])


# **3. nn.Module**

* nn(neural network)을 만들 때 상속 받아서 사용하는 추상 클래스


In [ ]:
import torch.nn as nn

In [ ]:
class MyLinear(nn.Module):
  def __init__(self,input_dim = 3, output_dim = 2):
    self.input_dim = input_dim # 입력하는 텐서의 차원 수
    self.output_dim = output_dim # 출력되는 텐서의 차원 수

    super().__init__() # 상속 ->  생성자 호출

    self.W = torch.FloatTensor(input_dim, output_dim)
    self.b = torch.FloatTensor(output_dim)
  
  def forward(self,x):
    y = torch.matmul(x,self.W) + self.b
    return y

In [ ]:
linear = MyLinear(3,2) # 클래스 객체를 만들고, input_dim, output_dim에 각각 3,2 대입
y = linear(x)          # linear 모델에 있는 forward 함수를 호출하고, 그때 파라미터에 x값을 대입시켜준다.

In [ ]:
print(y.size())

torch.Size([4, 2])


# **4. nn.Parameter**

* 신경망 파라미터를 optimizer에 전달해 줄 때 사용
```
optimizer = optim.SGD(model.parameters(), lr = 0.01, momnetum = 0.9)
```



In [ ]:
class MyLinear(nn.Module):
  def __init__(self,input_dim = 3, output_dim = 2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()

    # 신경망 파라미터를 optimizer에 전달
    self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
    self.b = nn.Parameter(torch.FloatTensor(output_dim))
  
  def forward(self,x):
    y = torch.matmul(x,self.W) + self.b
    return y

In [ ]:
linear = MyLinear(3,2) 
y = linear(x)  

In [ ]:
print(y.size())

torch.Size([4, 2])


In [ ]:
for p in linear.parameters():
  print(p)

Parameter containing:
tensor([[-3.4761e-18,  3.0649e-41],
        [-6.9524e-18,  6.1478e-41],
        [-1.0429e-17,  9.2217e-41]], requires_grad=True)
Parameter containing:
tensor([-3.4761e-18,  3.0649e-41], requires_grad=True)


# **5. nn.Linear를 통해 재구현하기**

In [ ]:
class MyLinear(nn.Module):
  def __init__(self,input_dim = 3, output_dim = 2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()

    self.linear = nn.Linear(input_dim, output_dim)
  
  def forward(self,x):
    y = self.linear(x)
    return y

In [ ]:
linear = MyLinear(3,2) 
y = linear(x)  

In [ ]:
print(y.size())

torch.Size([4, 2])


In [ ]:
for p in linear.parameters():
  print(p)

Parameter containing:
tensor([[-3.4760e-18,  3.0649e-41],
        [        nan,  6.1601e-41],
        [        nan,  9.2402e-41]], requires_grad=True)
Parameter containing:
tensor([-3.4759e-18,  3.0649e-41], requires_grad=True)
