# **1. GPU란?**

* GPU(Graphic Processing Unit)는 그래픽 처리, 특히 3D 모델링을 위한 프로세서로 탄생함
* 다량의 병렬 연산이 필요한 3D 랜더링, 딥러닝, 블록체인 등의 연산을 가속해주기 위해 사용함


# **2. GPU를 사용하는 방법**


In [ ]:
import torch
import torch.nn as nn # neural network를 구현하기 위한 모듈

In [ ]:
x = torch.cuda.FloatTensor(2,2)
print(x)
# No CUDA GPUs are available
# 에러가 발생할 경우, 런타임 유형변경에서 GPU 선택
# GPU가 여러 개 있는 경우 GPU 번호를 확인해야 함
# 같은 디바이스에 있는 텐서끼리만 연산이 가능하다.

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')


In [ ]:
x = torch.FloatTensor(2,2)
print(x)

tensor([[5.4355e+29, 3.0721e-41],
        [1.5975e-43, 1.3873e-43]])


In [ ]:
# GPU로 보냄
x.cuda()

tensor([[5.4355e+29, 3.0721e-41],
        [1.5975e-43, 1.3873e-43]], device='cuda:0')

In [ ]:
# GPU 0으로 지정하기
d = torch.device('cuda:0')

In [ ]:
# x의 값은 cpu에 남아 있고, x값의 복사본을 gpu에 보냄
x.cuda(device = d) # 현재 지정된 cuda로 보냄(device='cuda:0')

tensor([[5.4355e+29, 3.0721e-41],
        [1.5975e-43, 1.3873e-43]], device='cuda:0')

In [ ]:
x.device # x의 값은 실제로 계속 cpu에 저장되어 있다.

device(type='cpu')

In [ ]:
x = torch.cuda.FloatTensor(2,2)

In [ ]:
x = x.cpu() # x의 값을 다시 cpu에 보내기

In [ ]:
d = torch.device('cpu')
x = x.to(d)

In [ ]:
def print_params(model):
  for p in model.parameters():
    print(p)

In [ ]:
linear = nn.Linear(2,2)
print_params(linear)

Parameter containing:
tensor([[-0.1544,  0.3917],
        [-0.2520, -0.0543]], requires_grad=True)
Parameter containing:
tensor([-0.0805, -0.0865], requires_grad=True)


In [ ]:
linear = linear.cuda()
print_params(linear)

Parameter containing:
tensor([[-0.1544,  0.3917],
        [-0.2520, -0.0543]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0805, -0.0865], device='cuda:0', requires_grad=True)


In [ ]:
linear = linear.cpu()
print_params(linear)

Parameter containing:
tensor([[-0.1544,  0.3917],
        [-0.2520, -0.0543]], requires_grad=True)
Parameter containing:
tensor([-0.0805, -0.0865], requires_grad=True)


In [ ]:
d = torch.device('cuda:0')
linear = linear.to(d)
print_params(linear)

Parameter containing:
tensor([[-0.1544,  0.3917],
        [-0.2520, -0.0543]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0805, -0.0865], device='cuda:0', requires_grad=True)


In [ ]:
# linear.device # 모델은 device attribute를 제공하지 않는다.

AttributeError: ignored

In [ ]:
x = torch.cuda.FloatTensor(2,2)

In [ ]:
x.new(2,2) # new(): x와 같은 타입이면서 같은 디바이스에 있는 tensor를 생성해 준다.

tensor([[2.0000, 1.4110],
        [0.2520, 0.0543]], device='cuda:0')

In [ ]:
torch.zeros_like(x) # 텐서의 값을 0으로 다 채우기

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [ ]:
torch.ones_like(x) # 텐서의 값을 1로 다 채우기

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [ ]:
list(linear.parameters())[0].new(2,2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

> 다른 device에 있는 텐서끼리는 연산할 수 없다.