# **1. 파이토치(Pytorch)**

* Pytorch는 tensorflow와 함꼐 딥러닝에서 가장 널리 사용되는 framework
* 초기에는 Torch라는 이름으로 Lua 언어 기반으로 만들어졌으나, 이후 python기반으로 변경한 것이 Pytorch임
* 뉴욕대와 Facebook이 공동으로 만들었고, 가장 대중적이고 널리 사용되는 framework임

In [ ]:
import torch
print(torch.__version__)

1.10.0+cu111


### **1-1. Tensor**

* 텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한, 특수한 자료구조
* Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)함

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
import numpy as np

In [ ]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array) # 별도의 복사본(새로운 tensor) 생성 -> 메모리의 낭비가 발생
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [ ]:
x_np_1[0,0] = 10
print(x_np_1)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[1 2]
 [3 4]]


In [ ]:
x_np_2 = torch.as_tensor(np_array) # 뷰를 만듦 -> 메모리의 낭비가 x(동일한 메모리를 사용하고 있다.)
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [ ]:
x_np_2[0,0] = 10
print(x_np_2)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [ ]:
x_np_3 = torch.from_numpy(np_array) # 뷰를 만듬
print(x_np_3) 

tensor([[10,  2],
        [ 3,  4]])


In [ ]:
x_np_3[0,0] = 10
print(x_np_3)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [ ]:
# 텐서 -> ndArray
np_again = x_np_1.numpy()
print(np_again,type(np_again))

[[10  2]
 [ 3  4]] <class 'numpy.ndarray'>


In [ ]:
a = torch.ones(2,3)
print(a)
b = torch.zeros(2,3)
print(b)
c = torch.full((2,3),2)
print(c)
d = torch.empty(2,3) # 아무 값이나 들어간다.
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[5.4719e+24, 3.0850e-41, 3.3631e-44],
        [0.0000e+00,        nan, 1.0000e+00]])


In [ ]:
i = torch.eye(3) # 0과 1이 채워진다.(행렬을 만들고 사선으로 1이 채워짐)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
j = torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
k = torch.rand(2,2) # 0~1 사이의 임의의 수
l = torch.randn(2,2) # -1~1 사이의 임의의 수
print(k)
print(l)

tensor([[0.7201, 0.0655],
        [0.9738, 0.2980]])
tensor([[ 0.2547,  0.8735],
        [-0.5162,  0.6519]])


### **1-2. Tensor의 속성**


In [ ]:
tensor = torch.rand(3,4)

print(f'Shape of tensor : {tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device of tensor : cpu


In [ ]:
# 속성 변경
tensor = tensor.reshape(4,3)
tensor = tensor.int()
if torch.cuda.is_available(): # GPU를 사용하는 것이 가능하니??
  tensor = tensor.to('cuda') # GPU로 바꿔줘!!

print(f'Shape of tensor : {tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([4, 3])
Datatype of tensor : torch.int32
Device of tensor : cpu


### **1-3. 인덱싱과 슬라이싱**

In [ ]:
a = torch.arange(1,13).reshape(3,4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [ ]:
print(a[1]) # 1행
print(a[0,-1])

tensor([5, 6, 7, 8])
tensor(4)


In [ ]:
print(a[1:-1])

tensor([[5, 6, 7, 8]])


In [ ]:
print(a[:2,2:])

tensor([[3, 4],
        [7, 8]])


### **1-4.Transpose**

In [ ]:
a = torch.arange(16).reshape(2,2,4)
print(a,a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [ ]:
b = a.transpose(1,2)
print(b,b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [ ]:
c = a.permute(2,0,1)
print(c,c.shape) # transpose와 동일한 기능

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### **1-5. Tensor 연산**

In [ ]:
x = torch.tensor([[1,2],[3,4]],dtype = torch.float32)
y = torch.tensor([[5,6],[7,8]],dtype = torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [ ]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x@y) 
print("*" *30)
print(torch.add(x,y))
print(torch.subtract(x,y))
print(torch.multiply(x,y))
print(torch.divide(x,y))
print(torch.matmul(x,y))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
******************************
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [ ]:
# in - place 연산(복합대입연산자 느낌?)
print(x.add(y))
print(x)

print(x.add_(y)) # 기존의 x에 y를 더한 값을 다시 x에 저장하라~
print(x)
# 나머지도 비슷함

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [ ]:
z = torch.arange(1,11).reshape(2,5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [ ]:
sum1 = torch.sum(z,axis = 0)
sum2 = torch.sum(z,axis = 1)
sum3 = torch.sum(z,axis = -1)
print(sum1,sum1.shape)
print(sum2,sum2.shape)
print(sum3,sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [ ]:
a = torch.arange(24).reshape(4,6)
b = a.clone().detach() # 복사된 내용(ctrl+c)을 b에 붙여서 저장해라~(ctrl+v)
print(a,a.shape)
print(b,b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])


In [ ]:
c = torch.cat([a,b],axis = -1)
print(c,c.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]]) torch.Size([4, 12])
