# **1. 텐서플로우(TensorFlow) / 케라스(Keras)**

* 텐서플로우와 케라스는 ML 모댈을 개발하고 학습시키는 데 도움이 되는 핵심 오픈소스 라이브러리
* 케라스는 사용자가 텐서플로우를 좀 더 쉽고 편하게 사용할 수 있게 해주는 high level API 제공
* 텐서플로우 2.x에서는 케라스를 딥러닝의 공식 API로 채택하였고, 텐서플로우 내의 하나의 프레임워크로 개발되고 있음

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
print(tf.__version__)
print(keras.__version__)

2.7.0
2.7.0


### **1-1. 텐서(Tensor)**


Tensor는 multi-dimensional array를 나타내는 말로, Tensorflow의 기본 data type이다.

In [ ]:
hello = tf.constant([3,3],dtype = tf.float32) # constant: 상수
print(hello)

hello = tf.constant('Hello Tensor!')
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensor!', shape=(), dtype=string)


In [ ]:
x = tf.constant([[1.0,2.0],
                 [3.0,4.0]])
print(x)
print(type(x)) # EagerTensor : 어떤 형태로든 바뀔 수 있는 Tensorflow이다.(일반적인 파이썬 변수로도 변화가 가능하다.)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x_np = np.array([[1.0,2.0],
                 [3.0,4.0]])
x_list = [[1.0,2.0],
          [3.0,4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# numpy의 ndarray, python의 list를 tensor로 바꾸기
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(type(x_np))
print(type(x_list))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# tensor를 numpy의 ndarray로 바꾸기
x.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [ ]:
print(type(x.numpy()))

<class 'numpy.ndarray'>


In [ ]:
# 텐서플로우의 함수(넘파이와 비슷함)
a = tf.ones((2,3)) # 2행 3열짜리 행렬을 만들고 1로 다 채워라~
print(a)
b = tf.zeros((2,3))
print(b)
c = tf.fill((2,3),2)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [ ]:
# shape와 dtype이 복사 : _like()
d = tf.zeros_like(c)
print(d)
e = tf.ones_like(c)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
f = tf.eye(5)
print(f)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [ ]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
h = tf.random.uniform((2,2)) # 0부터 1 사이에서 난수 발생
print(h)

i = tf.random.normal((2,2)) # -1 ~ 1 사이에서 난수 발생
print(i)

tf.Tensor(
[[0.26693022 0.7836448 ]
 [0.93805134 0.5917542 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.6439646 -1.040267 ]
 [-1.3924251 -1.4457582]], shape=(2, 2), dtype=float32)


### **1-2. Tensor의 속성**

In [ ]:
tensor = tf.random.normal((3,4))
print(f'Shape: {tensor.shape}')  # f의 의미: format
print(f'Datatype: {tensor.dtype}')

Shape: (3, 4)
Datatype: <dtype: 'float32'>


In [ ]:
# 속성 변경
tensor = tf.reshape(tensor,(4,3))
tensor = tf.cast(tensor,tf.int32)
print(f'Shape: {tensor.shape}')
print(f'Datatype: {tensor.dtype}')

Shape: (4, 3)
Datatype: <dtype: 'int32'>


### **1-3. Variable**

* Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
* 딥러닝에서는 학습해야하는 가중치(weight, bias)들을 variable로 생성

In [ ]:
# 상수 -> 값의 변경이 되지 x
tensor = tf.ones((3,4))
print(tensor)

tensor[0,0] = 2

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


TypeError: ignored

In [ ]:
# variable 만들기, 값 변경하기
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [ ]:
initial_value = tf.random.normal(shape = (2,2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.6590352 , -2.1036096 ],
       [-1.9380941 ,  0.37710786]], dtype=float32)>


In [ ]:
# assign(value) : 값 설정
# assign_add(increment) : 더하기
# assign_sub(decrement) : 빼기

new_value = tf.random.normal(shape = (2,2))
print(new_value)
weight.assign(new_value)
print(weight)

added_value = tf.ones(shape = (2,2))
weight.assign_sub(added_value)
print(weight)

tf.Tensor(
[[ 0.13373886  0.34055322]
 [-0.9768692   1.1916069 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.13373886,  0.34055322],
       [-0.9768692 ,  1.1916069 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.8662611 , -0.6594468 ],
       [-1.9768692 ,  0.19160688]], dtype=float32)>


###**1-4. Indexing과 Slicing**

In [ ]:
a = tf.range(1,13)
print(a)

a = tf.reshape(a,(3,4)) # 행렬의 모양을 재배열함(요소 재배치)
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
# indexing을 하게 되면 차원이 감소할 수 있다.
print(a[1])
print(a[0,-1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# slicing : 슬라이싱은 차원이 유지된다.
print(a[1:-1])
print(a[:2,2:])

### **1-5. Transpose(차원 바꾸기)**


In [ ]:
a = tf.range(16)
print(a)
a = tf.reshape(a,(2,2,-1)) # matrix의 개수,행,열
                           # -1은 자동으로 만들라는 뜻
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [ ]:
print(a)
# transpose(전치할 행렬(transpose 해 줄 행렬), 차원의 순서(어떤 차원이 먼저 올 것인가), [오퍼레이션 명칭])
b = tf.transpose(a,(2,0,1))
print(b)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


### **1-6. Tensor 연산**


In [ ]:
x = tf.constant([[1,2],[3,4]],dtype = tf.float32)
y = tf.constant([[5,6],[7,8]],dtype = tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [ ]:
print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.multiply(x,y))
print(tf.divide(x,y))
print(tf.matmul(x,y)) # 행렬 계산 복습하기!!
print('*'*50)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x@y)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
**************************************************
tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [ ]:
z  = tf.range(1,11)
print(z)
z = tf.reshape(z,(2,5))
print(z)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [ ]:
# 요소의 합계
print(tf.reduce_sum(z))

# 다차원 배열에서의 요소의 합 구하기
sum1 = tf.reduce_sum(z,axis = 0) # 행끼리의 합계, 열마다 구분해서 구한다.
print(sum1)
sum2 = tf.reduce_sum(z,axis = 1) # 열끼리의 합계, 행마다 구분해서 구한다.
print(sum2)
sum3 = tf.reduce_sum(z,axis = -1) # 마지막 차원의 합계
print(sum3)

tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [ ]:
concat = tf.concat([z,z],axis = 0) # 행 방향으로 붙음
print(concat)
concat = tf.concat([z,z],axis = 1) # 열 방향으로 붙음
print(concat)
concat = tf.concat([z,z],axis = -1) # 마지막 요소의 방향으로 붙음(2차원 배열에서는 열 방향)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
